### ISSUE TITLE
No package 'libuecc' found?

### ISSUE THREAD

**Issue by briteming** [digineo/fastd#1]
hi,
in $GOPATH, I RAN:
go get -u -v github.com/digineo/fastd/cmd/fastd

the command exports:
...
# pkg-config --cflags libuecc
Package libuecc was not found in the pkg-config search path.
Perhaps you should add the directory containing `libuecc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libuecc' found
pkg-config: exit status 1

then i ran:
brew install libuecc
then i re-ran :
go get -u -v github.com/digineo/fastd/cmd/fastd

i still encounter the error above.
how to fix it?

**Comment by corny** [comment]
This application does only work on FreeBSD. Tests should work on Linux as well.
